Upd nnn plugins

diff --git a/config/nnn/plugins/imgur b/config/nnn/plugins/imgur
--- a/config/nnn/plugins/imgur
+++ b/config/nnn/plugins/imgur
@@ -28,11 +28,11 @@
 ##########################################################################
 
 # https://github.com/jomo/imgur-screenshot
-# https://imgur.com/tools
+# https://help.imgur.com/hc/en-us/articles/209592766-Tools-for-Imgur
 #
 # Slightly modified for `nnn` integration
 #
-# Shell: bash
+# Shell: Bash
 # Description: Upload an image file to imgur
 
 if [ "${1}" = "--debug" ]; then
@@ -112,28 +112,29 @@ check_update="true"
 
 settings_path="${HOME}/.config/imgur-screenshot/settings.conf"
 if [ -f "${settings_path}" ]; then
+  # shellcheck disable=SC1090
   source "${settings_path}"
 fi
 
 # dependency check
 if [ "${1}" = "--check" ]; then
-  (which grep &>/dev/null && echo "OK: found grep") || echo "ERROR: grep not found"
+  (type grep &>/dev/null && echo "OK: found grep") || echo "ERROR: grep not found"
   if is_mac; then
-    if which growlnotify &>/dev/null; then
+    if type growlnotify &>/dev/null; then
       echo "OK: found growlnotify"
-    elif which terminal-notifier &>/dev/null; then
+    elif type terminal-notifier &>/dev/null; then
       echo "OK: found terminal-notifier"
     else
       echo "ERROR: growlnotify nor terminal-notifier found"
     fi
-    (which screencapture &>/dev/null && echo "OK: found screencapture") || echo "ERROR: screencapture not found"
-    (which pbcopy &>/dev/null && echo "OK: found pbcopy") || echo "ERROR: pbcopy not found"
+    (type screencapture &>/dev/null && echo "OK: found screencapture") || echo "ERROR: screencapture not found"
+    (type pbcopy &>/dev/null && echo "OK: found pbcopy") || echo "ERROR: pbcopy not found"
   else
-    (which notify-send &>/dev/null && echo "OK: found notify-send") || echo "ERROR: notify-send (from libnotify-bin) not found"
-    (which scrot &>/dev/null && echo "OK: found scrot") || echo "ERROR: scrot not found"
-    (which xclip &>/dev/null && echo "OK: found xclip") || echo "ERROR: xclip not found"
+    (type notify-send &>/dev/null && echo "OK: found notify-send") || echo "ERROR: notify-send (from libnotify-bin) not found"
+    (type scrot &>/dev/null && echo "OK: found scrot") || echo "ERROR: scrot not found"
+    (type xclip &>/dev/null && echo "OK: found xclip") || echo "ERROR: xclip not found"
   fi
-  (which curl &>/dev/null && echo "OK: found curl") || echo "ERROR: curl not found"
+  (type curl &>/dev/null && echo "OK: found curl") || echo "ERROR: curl not found"
   exit 0
 fi
 
@@ -141,7 +142,7 @@ fi
 # notify <'ok'|'error'> <title> <text>
 function notify() {
   if is_mac; then
-    if which growlnotify &>/dev/null; then
+    if type growlnotify &>/dev/null; then
       growlnotify  --icon "${imgur_icon_path}" --iconpath "${imgur_icon_path}" --title "${2}" --message "${3}"
     else
       terminal-notifier -appIcon "${imgur_icon_path}" -contentImage "${imgur_icon_path}" -title "imgur: ${2}" -message "${3}"
@@ -172,8 +173,8 @@ function take_screenshot() {
 function check_for_update() {
   # exit non-zero on HTTP error, output only the body (no stats) but output errors, follow redirects, output everything to stdout
   remote_version="$(curl --compressed -fsSL --stderr - "https://api.github.com/repos/jomo/imgur-screenshot/releases" | grep -Em 1 --color 'tag_name":\s*".*"' | cut -d '"' -f 4)"
-  if ! [ -z "$remote_version" ]; then
-    if [ ! "${current_version}" = "${remote_version}" ] && [ ! -z "${current_version}" ] && [ ! -z "${remote_version}" ]; then
+  if [ -n "$remote_version" ]; then
+    if [ ! "${current_version}" = "${remote_version}" ] && [ -n "${current_version}" ] && [ -n "${remote_version}" ]; then
       echo "Update found!"
       echo "Version ${remote_version} is available (You have ${current_version})"
       notify ok "Update found" "Version ${remote_version} is available (You have ${current_version}). https://github.com/jomo/imgur-screenshot"
@@ -204,12 +205,13 @@ function load_access_token() {
   token_expire_time=0
   # check for saved access_token and its expiration date
   if [ -f "${credentials_file}" ]; then
+    # shellcheck disable=SC1090
     source "${credentials_file}"
   fi
   current_time="$(date +%s)"
   preemptive_refresh_time="$((10*60))"
   expired="$((current_time > (token_expire_time - preemptive_refresh_time)))"
-  if [ ! -z "${refresh_token}" ]; then
+  if [ -n "${refresh_token}" ]; then
     # token already set
     if [ "${expired}" -eq "0" ]; then
       # token expired
@@ -320,7 +322,7 @@ function upload_authenticated_image() {
     img_ext="$(grep -Eo '"link":\s*"[^"]+"' <<<"${response}" | cut -d "\"" -f 4 | rev | cut -d "." -f 1 | rev)" # "link" itself has ugly '\/' escaping and no https!
     del_id="$(grep -Eo '"deletehash":\s*"[^"]+"' <<<"${response}" | cut -d "\"" -f 4)"
 
-    if [ ! -z "${auto_delete}" ]; then
+    if [ -n "${auto_delete}" ]; then
       export -f delete_image
       echo "Deleting image in ${auto_delete} seconds."
       nohup /bin/bash -c "sleep ${auto_delete} && delete_image ${imgur_anon_id} ${del_id} ${log_file}" &
@@ -348,7 +350,7 @@ function upload_anonymous_image() {
     img_ext="$(grep -Eo '"link":\s*"[^"]+"' <<<"${response}" | cut -d "\"" -f 4 | rev | cut -d "." -f 1 | rev)" # "link" itself has ugly '\/' escaping and no https!
     del_id="$(grep -Eo '"deletehash":\s*"[^"]+"' <<<"${response}" | cut -d "\"" -f 4)"
 
-    if [ ! -z "${auto_delete}" ]; then
+    if [ -n "${auto_delete}" ]; then
       export -f delete_image
       echo "Deleting image in ${auto_delete} seconds."
       nohup /bin/bash -c "sleep ${auto_delete} && delete_image ${imgur_anon_id} ${del_id} ${log_file}" &
@@ -521,7 +523,7 @@ if [ -n "${album_title}" ]; then
     echo "Album '${album_title}' successfully created"
     album_id="$(grep -Eo '"id":\s*"[^"]+"' <<<"${response}" | cut -d "\"" -f 4)"
     del_id="$(grep -Eo '"deletehash":\s*"[^"]+"' <<<"${response}" | cut -d "\"" -f 4)"
-    handle_album_creation_success "http://imgur.com/a/${album_id}" "${del_id}" "${album_title}"
+    handle_album_creation_success "https://imgur.com/a/${album_id}" "${del_id}" "${album_title}"
 
     if [ "${login}" = "false" ]; then
       album_id="${del_id}"
